"""Membuat contoh isian template master data (fiktif) untuk mengetes dashboard."""
import pandas as pd
from datetime import date

def d(s): return pd.Timestamp(s)

yayasan = pd.DataFrame([
    dict(id_yayasan="Y01", nama_yayasan="Yayasan Perguruan Darma Agung", no_sk_badan_hukum="AHU-1234.AH.01.04.Tahun 2010",
         tgl_sk_badan_hukum=d("2010-05-12"), status_yayasan="Aktif", kota="Bandung", provinsi="Jawa Barat",
         sumber_data="Akta No. 12/2010", catatan=None),
    dict(id_yayasan="Y02", nama_yayasan="Yayasan Pendidikan Cendekia Mandiri", no_sk_badan_hukum="AHU-2211.AH.01.04.Tahun 2012",
         tgl_sk_badan_hukum=d("2012-02-20"), status_yayasan="Bersengketa", kota="Medan", provinsi="Sumatra Utara",
         sumber_data="Akta No. 7/2012", catatan="Dualisme kepengurusan sejak 2023"),
    dict(id_yayasan="Y03", nama_yayasan="Yayasan Wira Bhakti Nusantara", no_sk_badan_hukum="AHU-0087.AH.01.04.Tahun 2005",
         tgl_sk_badan_hukum=d("2005-09-01"), status_yayasan="Aktif", kota="Surabaya", provinsi="Jawa Timur",
         sumber_data="Akta No. 3/2005", catatan=None),
    dict(id_yayasan="Y04", nama_yayasan="Yayasan Pendidikan Insan Cita", no_sk_badan_hukum="AHU-3390.AH.01.04.Tahun 2015",
         tgl_sk_badan_hukum=d("2015-11-10"), status_yayasan="Aktif", kota="Makassar", provinsi="Sulawesi Selatan",
         sumber_data="Akta No. 21/2015", catatan=None),
    dict(id_yayasan="Y05", nama_yayasan="Yayasan Sinar Ilmu Sejahtera", no_sk_badan_hukum="AHU-0456.AH.01.04.Tahun 2009",
         tgl_sk_badan_hukum=d("2009-04-04"), status_yayasan="Aktif", kota="Palembang", provinsi="Sumatra Selatan",
         sumber_data="Akta No. 9/2009", catatan=None),
])

pt = pd.DataFrame([
    dict(kode_pt="P01", nama_pt="Universitas Darma Agung Nusantara", id_yayasan="Y01", jenis_pt="Universitas", status_pt="Aktif",
         no_izin_pt="123/E/O/2011", tgl_izin=d("2011-03-01"), wilayah_lldikti="LLDikti Wilayah I", akreditasi_pt="Baik Sekali",
         jumlah_mahasiswa_aktif=4500, jumlah_dosen_tetap=180, sumber_data="PDDikti", catatan=None),
    dict(kode_pt="P02", nama_pt="Institut Cendekia Mandiri", id_yayasan="Y02", jenis_pt="Institut", status_pt="Aktif",
         no_izin_pt="045/E/O/2013", tgl_izin=d("2013-01-15"), wilayah_lldikti="LLDikti Wilayah I", akreditasi_pt="Baik",
         jumlah_mahasiswa_aktif=2100, jumlah_dosen_tetap=95, sumber_data="PDDikti", catatan=None),
    dict(kode_pt="P03", nama_pt="STIE Wira Bhakti", id_yayasan="Y03", jenis_pt="Sekolah Tinggi", status_pt="Aktif",
         no_izin_pt="078/E/O/2006", tgl_izin=d("2006-08-01"), wilayah_lldikti="LLDikti Wilayah VII", akreditasi_pt="Baik",
         jumlah_mahasiswa_aktif=1200, jumlah_dosen_tetap=48, sumber_data="PDDikti", catatan=None),
    dict(kode_pt="P04", nama_pt="Politeknik Wira Bhakti", id_yayasan="Y03", jenis_pt="Politeknik", status_pt="Aktif",
         no_izin_pt="079/E/O/2008", tgl_izin=d("2008-02-01"), wilayah_lldikti="LLDikti Wilayah VII", akreditasi_pt="Baik Sekali",
         jumlah_mahasiswa_aktif=980, jumlah_dosen_tetap=40, sumber_data="PDDikti", catatan=None),
    dict(kode_pt="P05", nama_pt="Universitas Insan Cita", id_yayasan="Y04", jenis_pt="Universitas", status_pt="Aktif",
         no_izin_pt="301/E/O/2016", tgl_izin=d("2016-05-01"), wilayah_lldikti="LLDikti Wilayah IX", akreditasi_pt="Belum terakreditasi",
         jumlah_mahasiswa_aktif=3100, jumlah_dosen_tetap=130, sumber_data="PDDikti", catatan=None),
    dict(kode_pt="P06", nama_pt="Akademi Sinar Ilmu", id_yayasan="Y05", jenis_pt="Akademi", status_pt="Dalam pembinaan",
         no_izin_pt="012/E/O/2010", tgl_izin=d("2010-06-01"), wilayah_lldikti="LLDikti Wilayah II", akreditasi_pt="Kedaluwarsa",
         jumlah_mahasiswa_aktif=350, jumlah_dosen_tetap=18, sumber_data="PDDikti", catatan=None),
    dict(kode_pt="P07", nama_pt="STIE Sinar Ilmu (dahulu Yayasan Cahaya Bangsa)", id_yayasan="Y05", jenis_pt="Sekolah Tinggi",
         status_pt="Aktif", no_izin_pt="055/E/O/2009", tgl_izin=d("2009-07-01"), wilayah_lldikti="LLDikti Wilayah II",
         akreditasi_pt="Baik", jumlah_mahasiswa_aktif=760, jumlah_dosen_tetap=32, sumber_data="PDDikti", catatan=None),
])

riwayat_penyelenggara = pd.DataFrame([
    dict(id_penyelenggara="H01", kode_pt="P01", id_yayasan="Y01", tgl_mulai=d("2011-03-01"), tgl_akhir=None,
         jenis_perpindahan="Penyelenggara awal", id_yayasan_sebelumnya=None, alasan_alih_kelola=None,
         no_sk_alih_kelola=None, tgl_sk_alih_kelola=None, catatan=None),
    dict(id_penyelenggara="H02", kode_pt="P02", id_yayasan="Y02", tgl_mulai=d("2013-01-15"), tgl_akhir=None,
         jenis_perpindahan="Penyelenggara awal", id_yayasan_sebelumnya=None, alasan_alih_kelola=None,
         no_sk_alih_kelola=None, tgl_sk_alih_kelola=None, catatan=None),
    dict(id_penyelenggara="H03", kode_pt="P03", id_yayasan="Y03", tgl_mulai=d("2006-08-01"), tgl_akhir=None,
         jenis_perpindahan="Penyelenggara awal", id_yayasan_sebelumnya=None, alasan_alih_kelola=None,
         no_sk_alih_kelola=None, tgl_sk_alih_kelola=None, catatan=None),
    dict(id_penyelenggara="H04", kode_pt="P04", id_yayasan="Y03", tgl_mulai=d("2008-02-01"), tgl_akhir=None,
         jenis_perpindahan="Penyelenggara awal", id_yayasan_sebelumnya=None, alasan_alih_kelola=None,
         no_sk_alih_kelola=None, tgl_sk_alih_kelola=None, catatan=None),
    dict(id_penyelenggara="H05", kode_pt="P05", id_yayasan="Y04", tgl_mulai=d("2016-05-01"), tgl_akhir=None,
         jenis_perpindahan="Penyelenggara awal", id_yayasan_sebelumnya=None, alasan_alih_kelola=None,
         no_sk_alih_kelola=None, tgl_sk_alih_kelola=None, catatan=None),
    dict(id_penyelenggara="H06", kode_pt="P06", id_yayasan="Y05", tgl_mulai=d("2010-06-01"), tgl_akhir=None,
         jenis_perpindahan="Penyelenggara awal", id_yayasan_sebelumnya=None, alasan_alih_kelola=None,
         no_sk_alih_kelola=None, tgl_sk_alih_kelola=None, catatan=None),
    dict(id_penyelenggara="H07", kode_pt="P07", id_yayasan="Y05", tgl_mulai=d("2022-04-01"), tgl_akhir=None,
         jenis_perpindahan="Alih kelola ke yayasan lain", id_yayasan_sebelumnya="Y00-lama",
         alasan_alih_kelola="Sengketa yayasan", no_sk_alih_kelola="112/AHU/2022", tgl_sk_alih_kelola=d("2022-04-01"),
         catatan="Sebelumnya di bawah Yayasan Cahaya Bangsa"),
])

akta = pd.DataFrame([
    dict(id_akta="A01", id_yayasan="Y01", no_akta=3, tgl_akta=d("2010-04-20"), tgl_berlaku=d("2010-05-12"),
         no_sk_kemenkum="AHU-1234.AH.01.04.Tahun 2010", tgl_sk_kemenkum=d("2010-05-12"), jenis_perubahan="Pendirian",
         ringkasan_perubahan="Pendirian yayasan", pasal_berubah=None, ubah_kewenangan_terhadap_pt="Tidak",
         nama_file_sumber="akta_3_2010.pdf", catatan=None),
    dict(id_akta="A02", id_yayasan="Y01", no_akta=18, tgl_akta=d("2020-06-15"), tgl_berlaku=d("2020-07-01"),
         no_sk_kemenkum="AHU-AH.01.06-0123", tgl_sk_kemenkum=d("2020-07-01"), jenis_perubahan="Perubahan organ",
         ringkasan_perubahan="Penggantian ketua pengurus dan bendahara", pasal_berubah="Pasal 12",
         ubah_kewenangan_terhadap_pt="Tidak", nama_file_sumber="akta_18_2020.pdf", catatan=None),
    dict(id_akta="A03", id_yayasan="Y02", no_akta=7, tgl_akta=d("2012-02-05"), tgl_berlaku=d("2012-02-20"),
         no_sk_kemenkum="AHU-2211.AH.01.04.Tahun 2012", tgl_sk_kemenkum=d("2012-02-20"), jenis_perubahan="Pendirian",
         ringkasan_perubahan="Pendirian yayasan", pasal_berubah=None, ubah_kewenangan_terhadap_pt="Tidak",
         nama_file_sumber="akta_7_2012.pdf", catatan=None),
    dict(id_akta="A04", id_yayasan="Y02", no_akta=25, tgl_akta=d("2022-11-01"), tgl_berlaku=d("2022-11-15"),
         no_sk_kemenkum="AHU-AH.01.06-0900", tgl_sk_kemenkum=d("2022-11-15"), jenis_perubahan="Perubahan AD dan organ",
         ringkasan_perubahan="Penggantian seluruh pengurus lewat RUPS internal yang disengketakan", pasal_berubah="Pasal 8; Pasal 15",
         ubah_kewenangan_terhadap_pt="Ya", nama_file_sumber="akta_25_2022.pdf", catatan="Diklaim tidak sah oleh kubu lama"),
    dict(id_akta="A05", id_yayasan="Y02", no_akta=26, tgl_akta=d("2023-01-10"), tgl_berlaku=d("2023-01-20"),
         no_sk_kemenkum=None, tgl_sk_kemenkum=None, jenis_perubahan="Perubahan organ",
         ringkasan_perubahan="Susunan pengurus versi kubu lama (tandingan akta No. 25/2022)", pasal_berubah="Pasal 8",
         ubah_kewenangan_terhadap_pt="Tidak", nama_file_sumber="akta_26_2023.pdf", catatan="Indikasi dualisme kepengurusan"),
    dict(id_akta="A06", id_yayasan="Y03", no_akta=5, tgl_akta=d("2005-08-15"), tgl_berlaku=d("2005-09-01"),
         no_sk_kemenkum="AHU-0087.AH.01.04.Tahun 2005", tgl_sk_kemenkum=d("2005-09-01"), jenis_perubahan="Pendirian",
         ringkasan_perubahan="Pendirian yayasan", pasal_berubah=None, ubah_kewenangan_terhadap_pt="Tidak",
         nama_file_sumber="akta_5_2005.pdf", catatan=None),
    dict(id_akta="A07", id_yayasan="Y04", no_akta=21, tgl_akta=d("2015-10-20"), tgl_berlaku=d("2015-11-10"),
         no_sk_kemenkum="AHU-3390.AH.01.04.Tahun 2015", tgl_sk_kemenkum=d("2015-11-10"), jenis_perubahan="Pendirian",
         ringkasan_perubahan="Pendirian yayasan", pasal_berubah=None, ubah_kewenangan_terhadap_pt="Tidak",
         nama_file_sumber="akta_21_2015.pdf", catatan=None),
    dict(id_akta="A08", id_yayasan="Y04", no_akta=30, tgl_akta=d("2023-06-01"), tgl_berlaku=d("2023-06-15"),
         no_sk_kemenkum="AHU-AH.01.06-1500", tgl_sk_kemenkum=d("2023-06-15"), jenis_perubahan="Perubahan AD",
         ringkasan_perubahan="Perluasan kewenangan yayasan atas pengangkatan wakil rektor", pasal_berubah="Pasal 14",
         ubah_kewenangan_terhadap_pt="Ya", nama_file_sumber="akta_30_2023.pdf", catatan="4 bulan sebelum pergantian rektor P05"),
    dict(id_akta="A09", id_yayasan="Y05", no_akta=9, tgl_akta=d("2009-03-20"), tgl_berlaku=d("2009-04-04"),
         no_sk_kemenkum="AHU-0456.AH.01.04.Tahun 2009", tgl_sk_kemenkum=d("2009-04-04"), jenis_perubahan="Pendirian",
         ringkasan_perubahan="Pendirian yayasan", pasal_berubah=None, ubah_kewenangan_terhadap_pt="Tidak",
         nama_file_sumber="akta_9_2009.pdf", catatan=None),
])

organ_yayasan = pd.DataFrame([
    dict(id_organ="O01", id_yayasan="Y01", id_akta_sumber="A02", nama_lengkap="Dr. Budi Santoso, M.M.", nik="3201010101800001",
         jabatan_yayasan="Ketua Pengurus", tgl_mulai=d("2020-07-01"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None, catatan=None),
    dict(id_organ="O02", id_yayasan="Y01", id_akta_sumber="A01", nama_lengkap="Hendra Wijaya", nik=None,
         jabatan_yayasan="Pembina", tgl_mulai=d("2010-05-12"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None, catatan=None),
    dict(id_organ="O03", id_yayasan="Y01", id_akta_sumber="A02", nama_lengkap="Ratna Kusuma", nik=None,
         jabatan_yayasan="Bendahara", tgl_mulai=d("2020-07-01"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None, catatan=None),
    dict(id_organ="O04", id_yayasan="Y02", id_akta_sumber="A04", nama_lengkap="Andi Prasetyo", nik="1271020202750001",
         jabatan_yayasan="Ketua Pengurus", tgl_mulai=d("2022-11-15"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None,
         catatan="Versi akta No. 25/2022"),
    dict(id_organ="O05", id_yayasan="Y02", id_akta_sumber="A05", nama_lengkap="Yusuf Hakim", nik=None,
         jabatan_yayasan="Ketua Pengurus", tgl_mulai=d("2023-01-20"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None,
         catatan="Versi tandingan, akta No. 26/2023"),
    dict(id_organ="O06", id_yayasan="Y03", id_akta_sumber="A06", nama_lengkap="Slamet Riyadi", nik=None,
         jabatan_yayasan="Ketua Pengurus", tgl_mulai=d("2005-09-01"), tgl_akhir=d("2026-08-31"), status_periode="Berjalan", alasan_berhenti=None,
         catatan="Masa jabatan menurut AD sudah lama berakhir, belum ada akta pembaruan"),
    dict(id_organ="O07", id_yayasan="Y03", id_akta_sumber="A06", nama_lengkap="Dewi Anggraini", nik=None,
         jabatan_yayasan="Bendahara", tgl_mulai=d("2005-09-01"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None, catatan=None),
    dict(id_organ="O08", id_yayasan="Y04", id_akta_sumber="A07", nama_lengkap="Prof. Dr. Siti Aminah, M.Si.", nik="7371030303650001",
         jabatan_yayasan="Ketua Pengurus", tgl_mulai=d("2015-11-10"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None, catatan=None),
    dict(id_organ="O09", id_yayasan="Y05", id_akta_sumber="A09", nama_lengkap="Bambang Sutrisno", nik=None,
         jabatan_yayasan="Ketua Pengurus", tgl_mulai=d("2009-04-04"), tgl_akhir=None, status_periode="Berjalan", alasan_berhenti=None, catatan=None),
    dict(id_organ="O10", id_yayasan="Y05", id_akta_sumber="A09", nama_lengkap="Tuti Herawati", nik=None,
         jabatan_yayasan="Pengawas", tgl_mulai=d("2009-04-04"), tgl_akhir=d("2019-04-03"), status_periode="Selesai", alasan_berhenti="Habis masa jabatan", catatan=None),
])

pimpinan_pt = pd.DataFrame([
    dict(id_pimpinan="K01", kode_pt="P01", id_yayasan="Y01", nama_lengkap="Prof. Dr. Wayan Sudira", nik=None,
         jabatan_pt="Rektor", status_definitif="Definitif", tgl_mulai=d("2019-01-01"), tgl_akhir=None,
         no_sk_pengangkatan="011/YPDA/SK/2019", tgl_sk_pengangkatan=d("2018-12-10"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti=None, ada_dok_penjaringan="Ya", ada_dok_pertimbangan_senat="Ya", ada_dok_pemberhentian="Tidak diketahui",
         merangkap_organ_yayasan="Tidak", catatan=None),
    dict(id_pimpinan="K02", kode_pt="P01", id_yayasan="Y01", nama_lengkap="Budi Santoso", nik="3201010101800001",
         jabatan_pt="Wakil Rektor II", status_definitif="Definitif", tgl_mulai=d("2022-01-01"), tgl_akhir=None,
         no_sk_pengangkatan="045/YPDA/SK/2022", tgl_sk_pengangkatan=d("2021-12-15"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti=None, ada_dok_penjaringan="Tidak", ada_dok_pertimbangan_senat="Tidak", ada_dok_pemberhentian="Tidak diketahui",
         merangkap_organ_yayasan="Ya", catatan="Sekaligus Ketua Pengurus Yayasan Y01 (lihat organ_yayasan O01)"),
    dict(id_pimpinan="K03", kode_pt="P02", id_yayasan="Y02", nama_lengkap="Dr. Siti Marlina", nik=None,
         jabatan_pt="Rektor", status_definitif="Definitif", tgl_mulai=d("2019-06-01"), tgl_akhir=d("2022-08-01"),
         no_sk_pengangkatan="008/YCM/SK/2019", tgl_sk_pengangkatan=d("2019-05-20"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti="Diberhentikan", ada_dok_penjaringan="Ya", ada_dok_pertimbangan_senat="Ya", ada_dok_pemberhentian="Tidak",
         merangkap_organ_yayasan="Tidak", catatan="Diberhentikan tak lama setelah pergantian pengurus yayasan (akta No. 25/2022)"),
    dict(id_pimpinan="K04", kode_pt="P02", id_yayasan="Y02", nama_lengkap="Ir. Hasan Basri", nik=None,
         jabatan_pt="Rektor", status_definitif="Plt", tgl_mulai=d("2022-08-05"), tgl_akhir=d("2023-02-01"),
         no_sk_pengangkatan="050/YCM/SK/2022", tgl_sk_pengangkatan=d("2022-08-05"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti="Mengundurkan diri", ada_dok_penjaringan="Tidak", ada_dok_pertimbangan_senat="Tidak", ada_dok_pemberhentian="Ya",
         merangkap_organ_yayasan="Tidak diketahui", catatan=None),
    dict(id_pimpinan="K05", kode_pt="P02", id_yayasan="Y02", nama_lengkap="Yusuf Hakim", nik=None,
         jabatan_pt="Rektor", status_definitif="Plt", tgl_mulai=d("2023-02-02"), tgl_akhir=None,
         no_sk_pengangkatan="002/YCM/SK/2023", tgl_sk_pengangkatan=d("2023-01-25"), pejabat_pengangkat="Ketua Pengurus Yayasan (versi tandingan)",
         alasan_berhenti=None, ada_dok_penjaringan="Tidak", ada_dok_pertimbangan_senat="Tidak", ada_dok_pemberhentian="Tidak diketahui",
         merangkap_organ_yayasan="Ya", catatan="Sekaligus Ketua Pengurus Yayasan versi tandingan (O05); Plt lebih dari 3 tahun"),
    dict(id_pimpinan="K06", kode_pt="P03", id_yayasan="Y03", nama_lengkap="Dr. Ahmad Fauzi", nik=None,
         jabatan_pt="Ketua", status_definitif="Definitif", tgl_mulai=d("2015-01-01"), tgl_akhir=None,
         no_sk_pengangkatan="003/YWB/SK/2015", tgl_sk_pengangkatan=d("2014-12-10"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti=None, ada_dok_penjaringan="Tidak diketahui", ada_dok_pertimbangan_senat="Tidak diketahui",
         ada_dok_pemberhentian="Tidak diketahui", merangkap_organ_yayasan="Tidak", catatan="Menjabat 11 tahun berturut-turut"),
    dict(id_pimpinan="K07", kode_pt="P04", id_yayasan="Y03", nama_lengkap="Rina Kartika", nik=None,
         jabatan_pt="Direktur", status_definitif="Definitif", tgl_mulai=d("2021-03-01"), tgl_akhir=None,
         no_sk_pengangkatan="014/YWB/SK/2021", tgl_sk_pengangkatan=d("2021-02-15"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti=None, ada_dok_penjaringan="Ya", ada_dok_pertimbangan_senat="Ya", ada_dok_pemberhentian="Tidak diketahui",
         merangkap_organ_yayasan="Tidak", catatan=None),
    dict(id_pimpinan="K08", kode_pt="P05", id_yayasan="Y04", nama_lengkap="Prof. Dr. Siti Aminah, M.Si.", nik="7371030303650001",
         jabatan_pt="Rektor", status_definitif="Definitif", tgl_mulai=d("2019-01-01"), tgl_akhir=d("2023-09-01"),
         no_sk_pengangkatan="019/YPIC/SK/2019", tgl_sk_pengangkatan=d("2018-12-01"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti="Diberhentikan", ada_dok_penjaringan="Ya", ada_dok_pertimbangan_senat="Tidak", ada_dok_pemberhentian="Tidak",
         merangkap_organ_yayasan="Ya", catatan="Rangkap Ketua Pengurus Yayasan (O08); diberhentikan 3 bulan setelah akta No. 30/2023"),
    dict(id_pimpinan="K09", kode_pt="P05", id_yayasan="Y04", nama_lengkap="Drs. Bahtiar Rahman", nik=None,
         jabatan_pt="Rektor", status_definitif="Pj", tgl_mulai=d("2023-09-05"), tgl_akhir=None,
         no_sk_pengangkatan="055/YPIC/SK/2023", tgl_sk_pengangkatan=d("2023-09-05"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti=None, ada_dok_penjaringan="Tidak", ada_dok_pertimbangan_senat="Tidak", ada_dok_pemberhentian="Tidak diketahui",
         merangkap_organ_yayasan="Tidak diketahui", catatan=None),
    dict(id_pimpinan="K10", kode_pt="P06", id_yayasan="Y05", nama_lengkap="Sutan Malik", nik=None,
         jabatan_pt="Direktur", status_definitif="Definitif", tgl_mulai=d("2018-01-01"), tgl_akhir=None,
         no_sk_pengangkatan="004/YSI/SK/2018", tgl_sk_pengangkatan=d("2017-12-01"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti=None, ada_dok_penjaringan="Ya", ada_dok_pertimbangan_senat="Ya", ada_dok_pemberhentian="Tidak diketahui",
         merangkap_organ_yayasan="Tidak", catatan=None),
    dict(id_pimpinan="K11", kode_pt="P07", id_yayasan="Y05", nama_lengkap="Dr. Endang Suryani", nik=None,
         jabatan_pt="Ketua", status_definitif="Definitif", tgl_mulai=d("2022-04-01"), tgl_akhir=None,
         no_sk_pengangkatan="001/YSI/SK/2022", tgl_sk_pengangkatan=d("2022-03-20"), pejabat_pengangkat="Ketua Pengurus Yayasan",
         alasan_berhenti=None, ada_dok_penjaringan="Ya", ada_dok_pertimbangan_senat="Ya", ada_dok_pemberhentian="Tidak diketahui",
         merangkap_organ_yayasan="Tidak", catatan="Diangkat mengikuti alih kelola dari Yayasan Cahaya Bangsa"),
])

aturan_statuta = pd.DataFrame([
    dict(id_statuta="S01", kode_pt="P01", versi_statuta="Statuta 2018", no_peraturan_statuta="SK Yayasan No. 5/2018",
         tgl_berlaku=d("2018-01-01"), tgl_berakhir=None, pengangkat_rektor="Yayasan setelah pertimbangan senat",
         wajib_penjaringan="Ya", wajib_pertimbangan_senat="Ya", masa_jabatan_rektor_tahun=4, maks_periode_rektor=2,
         batas_usia_rektor=65, larangan_rangkap_organ_yayasan="Ya",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri; melanggar peraturan; berhalangan tetap",
         prosedur_pemberhentian_diatur="Ya", wajib_pertimbangan_senat_berhenti="Ya", hak_membela_diri="Ya",
         ada_senat="Ya", ada_spi="Ya", yayasan_berwenang_akademik="Tidak", pasal_pengangkatan="Pasal 25 ayat 1-3",
         pasal_pemberhentian="Pasal 27", kutipan_pengangkatan="Rektor diangkat dan diberhentikan oleh Yayasan setelah mendapat pertimbangan Senat [contoh fiktif].",
         kutipan_pemberhentian=None, catatan=None),
    dict(id_statuta="S02", kode_pt="P02", versi_statuta="Statuta 2013", no_peraturan_statuta="SK Yayasan No. 2/2013",
         tgl_berlaku=d("2013-01-15"), tgl_berakhir=None, pengangkat_rektor="Yayasan",
         wajib_penjaringan="Tidak diatur", wajib_pertimbangan_senat="Tidak diatur", masa_jabatan_rektor_tahun=4, maks_periode_rektor=2,
         batas_usia_rektor=None, larangan_rangkap_organ_yayasan="Tidak diatur",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri; berhalangan tetap",
         prosedur_pemberhentian_diatur="Tidak diatur", wajib_pertimbangan_senat_berhenti="Tidak diatur", hak_membela_diri="Tidak diatur",
         ada_senat="Ya", ada_spi="Tidak diatur", yayasan_berwenang_akademik="Tidak diatur", pasal_pengangkatan="Pasal 12",
         pasal_pemberhentian="Pasal 14", kutipan_pengangkatan=None, kutipan_pemberhentian=None,
         catatan="Statuta belum diperbarui sejak 2013"),
    dict(id_statuta="S03", kode_pt="P03", versi_statuta="Statuta 2015", no_peraturan_statuta="SK Yayasan No. 4/2015",
         tgl_berlaku=d("2015-01-01"), tgl_berakhir=None, pengangkat_rektor="Yayasan setelah pertimbangan senat",
         wajib_penjaringan="Ya", wajib_pertimbangan_senat="Ya", masa_jabatan_rektor_tahun=4, maks_periode_rektor=2,
         batas_usia_rektor=65, larangan_rangkap_organ_yayasan="Ya",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri; melanggar peraturan; berhalangan tetap",
         prosedur_pemberhentian_diatur="Ya", wajib_pertimbangan_senat_berhenti="Ya", hak_membela_diri="Ya",
         ada_senat="Ya", ada_spi="Ya", yayasan_berwenang_akademik="Tidak", pasal_pengangkatan="Pasal 20",
         pasal_pemberhentian="Pasal 22", kutipan_pengangkatan=None, kutipan_pemberhentian=None,
         catatan="Ketua sudah 2 periode lebih (menjabat sejak 2015 tanpa pergantian)"),
    dict(id_statuta="S04", kode_pt="P04", versi_statuta="Statuta 2016", no_peraturan_statuta="SK Yayasan No. 6/2016",
         tgl_berlaku=d("2016-01-01"), tgl_berakhir=None, pengangkat_rektor="Yayasan setelah pertimbangan senat",
         wajib_penjaringan="Ya", wajib_pertimbangan_senat="Ya", masa_jabatan_rektor_tahun=4, maks_periode_rektor=2,
         batas_usia_rektor=65, larangan_rangkap_organ_yayasan="Ya",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri; melanggar peraturan; berhalangan tetap",
         prosedur_pemberhentian_diatur="Ya", wajib_pertimbangan_senat_berhenti="Ya", hak_membela_diri="Ya",
         ada_senat="Ya", ada_spi="Ya", yayasan_berwenang_akademik="Tidak", pasal_pengangkatan="Pasal 18",
         pasal_pemberhentian="Pasal 20", kutipan_pengangkatan=None, kutipan_pemberhentian=None, catatan=None),
    dict(id_statuta="S05", kode_pt="P05", versi_statuta="Statuta 2016", no_peraturan_statuta="SK Yayasan No. 3/2016",
         tgl_berlaku=d("2016-01-01"), tgl_berakhir=d("2023-06-15"), pengangkat_rektor="Yayasan setelah pertimbangan senat",
         wajib_penjaringan="Ya", wajib_pertimbangan_senat="Ya", masa_jabatan_rektor_tahun=4, maks_periode_rektor=2,
         batas_usia_rektor=65, larangan_rangkap_organ_yayasan="Ya",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri; melanggar peraturan; berhalangan tetap",
         prosedur_pemberhentian_diatur="Ya", wajib_pertimbangan_senat_berhenti="Ya", hak_membela_diri="Ya",
         ada_senat="Ya", ada_spi="Ya", yayasan_berwenang_akademik="Tidak", pasal_pengangkatan="Pasal 25",
         pasal_pemberhentian="Pasal 27", kutipan_pengangkatan=None, kutipan_pemberhentian=None, catatan=None),
    dict(id_statuta="S06", kode_pt="P05", versi_statuta="Statuta 2023", no_peraturan_statuta="SK Yayasan No. 9/2023",
         tgl_berlaku=d("2023-06-15"), tgl_berakhir=None, pengangkat_rektor="Yayasan",
         wajib_penjaringan="Tidak", wajib_pertimbangan_senat="Tidak", masa_jabatan_rektor_tahun=4, maks_periode_rektor=2,
         batas_usia_rektor=65, larangan_rangkap_organ_yayasan="Tidak diatur",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri; berhalangan tetap",
         prosedur_pemberhentian_diatur="Tidak", wajib_pertimbangan_senat_berhenti="Tidak", hak_membela_diri="Tidak diatur",
         ada_senat="Ya", ada_spi="Tidak diatur", yayasan_berwenang_akademik="Ya", pasal_pengangkatan="Pasal 25",
         pasal_pemberhentian="Pasal 27", kutipan_pengangkatan="Rektor dan Wakil Rektor diangkat oleh Yayasan [contoh fiktif].",
         kutipan_pemberhentian=None, catatan="Direvisi 4 bulan sebelum pemberhentian Rektor (lihat akta No. 30/2023)"),
    dict(id_statuta="S07", kode_pt="P06", versi_statuta="Statuta 2010", no_peraturan_statuta="SK Yayasan No. 1/2010",
         tgl_berlaku=d("2010-06-01"), tgl_berakhir=None, pengangkat_rektor="Yayasan",
         wajib_penjaringan="Tidak diatur", wajib_pertimbangan_senat="Tidak diatur", masa_jabatan_rektor_tahun=4, maks_periode_rektor=None,
         batas_usia_rektor=None, larangan_rangkap_organ_yayasan="Tidak diatur",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri",
         prosedur_pemberhentian_diatur="Tidak diatur", wajib_pertimbangan_senat_berhenti="Tidak diatur", hak_membela_diri="Tidak diatur",
         ada_senat="Tidak diatur", ada_spi="Tidak diatur", yayasan_berwenang_akademik="Tidak diatur", pasal_pengangkatan="Pasal 9",
         pasal_pemberhentian="Pasal 10", kutipan_pengangkatan=None, kutipan_pemberhentian=None,
         catatan="Statuta sangat minim, belum diperbarui sejak 2010"),
    dict(id_statuta="S08", kode_pt="P07", versi_statuta="Statuta 2022", no_peraturan_statuta="SK Yayasan No. 2/2022",
         tgl_berlaku=d("2022-04-01"), tgl_berakhir=None, pengangkat_rektor="Yayasan setelah pertimbangan senat",
         wajib_penjaringan="Ya", wajib_pertimbangan_senat="Ya", masa_jabatan_rektor_tahun=4, maks_periode_rektor=2,
         batas_usia_rektor=65, larangan_rangkap_organ_yayasan="Ya",
         alasan_pemberhentian_sah="habis masa jabatan; mengundurkan diri; melanggar peraturan; berhalangan tetap",
         prosedur_pemberhentian_diatur="Ya", wajib_pertimbangan_senat_berhenti="Ya", hak_membela_diri="Ya",
         ada_senat="Ya", ada_spi="Ya", yayasan_berwenang_akademik="Tidak", pasal_pengangkatan="Pasal 22",
         pasal_pemberhentian="Pasal 24", kutipan_pengangkatan=None, kutipan_pemberhentian=None, catatan=None),
])

riwayat_perubahan = pd.DataFrame([
    dict(id_perubahan="R01", jenis_dokumen="Anggaran Dasar", id_entitas="Y02", tgl_perubahan=d("2022-11-15"),
         jenis_perubahan="Perubahan kewenangan", menyentuh_pasal_pimpinan="Ya",
         ringkasan_perubahan="Perubahan pengurus lewat akta No. 25/2022 yang disengketakan", dasar_perubahan=None, catatan=None),
    dict(id_perubahan="R02", jenis_dokumen="Statuta", id_entitas="P05", tgl_perubahan=d("2023-06-15"),
         jenis_perubahan="Perubahan pengangkatan/pemberhentian pimpinan", menyentuh_pasal_pimpinan="Ya",
         ringkasan_perubahan="Statuta direvisi, kewenangan pengangkatan/pemberhentian rektor dipindah penuh ke yayasan",
         dasar_perubahan="SK Yayasan No. 9/2023", catatan="4 bulan sebelum Rektor diberhentikan"),
])

SHEETS = dict(yayasan=yayasan, pt=pt, riwayat_penyelenggara=riwayat_penyelenggara, akta=akta,
              organ_yayasan=organ_yayasan, pimpinan_pt=pimpinan_pt, aturan_statuta=aturan_statuta,
              riwayat_perubahan=riwayat_perubahan)

if __name__ == "__main__":
    with pd.ExcelWriter("/mnt/user-data/outputs/Contoh_Data_Terisi_Fiktif.xlsx", engine="openpyxl") as w:
        for name, df in SHEETS.items():
            df.to_excel(w, sheet_name=name, index=False)
    print("selesai", {k: v.shape for k, v in SHEETS.items()})
